import pytest
import httpx

API_URL = "http://wiosna97.fvds.ru:8000/v2"

@pytest.mark.asyncio
async def test_simple_batch_submission():
    print()
    user_data = {
        "username": "test",
        "password": "test"
    }
    batch_data = {"submissions": []}
    submission_data = {
        "language_id": 4,
        "source_code": "I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8c3RkaW8uaD4KdXNpbmcgbmFtZXNwYWNlIHN0ZDsgCiAKbG9uZyBhLGI7CiAKaW50IG1haW4oKXsKICAgICAKICBzY2FuZigiJWxkJWxkIiwmYSwmYik7CiAgcHJpbnRmKCIlbGQiLGErYik7CiAgcmV0dXJuIDA7Cn0=",
        "stdin": "Mgoz",
        "expected_output": "NQ==",
        "compiler_options": None,
        "command_line_args": None,
        "time_limit": 1,
        "extra_time": 0.5,
        "wall_time_limit": 3,
        "memory_limit": 128000,
        "redirect_stderr_to_stdout": True,
        "enable_network": False,
        "max_file_size": 1024
    }
    for i in range(20):
        batch_data["submissions"].append(submission_data)
    async with httpx.AsyncClient() as client:
        print("Тест 1: Создание пакетной отправки")
        resp = await client.post(f"{API_URL}/auth/login/", json=user_data)
        assert resp.status_code == 200, f"Auth error: {resp.text}"
        tokens = resp.json()
        access_token = tokens["access_token"]
        
        headers = {"Authorization": f"Bearer {access_token}"}
        resp = await client.post(f"{API_URL}/submissions/batch/", json=batch_data, headers=headers)
        assert resp.status_code == 201, resp.text
        print(f"Результаты теста: HTTP {resp.status_code} => {resp.json()['batch_token']}")

@pytest.mark.asyncio
async def test_complex_batch_submission():
    print()
    user_data = {
        "username": "test",
        "password": "test"
    }
    batch_data = {"submissions": []}
    submission_data = {
        "language_id": 4,
        "source_code": "I2luY2x1ZGUgPHN0ZGlvLmg+CnVzaW5nIG5hbWVzcGFjZSBzdGQ7CiAKaW50IG1haW4oKSB7CiAgICBpbnQgbiwgbTsKICAgIHNjYW5mKCIlZCAlZCIsICZuLCAmbSk7CiAgICBib29sIGJbbSArIDFdID0ge307CiAgICBmb3IgKGludCBpID0gMjsgaSA8PSBtOyBpKyspIHsKICAgICAgICBiW2ldID0gdHJ1ZTsKICAgIH0KICAgIGZvciAoaW50IGkgPSAyOyBpIDw9IG07IGkrKykgewogICAgICAgIGlmIChiW2ldKSB7CiAgICAgICAgICAgIGZvciAoaW50IGogPSAyOyBpICogaiA8PSBtOyBqKyspIHsKICAgICAgICAgICAgICAgIGJbaSAqIGpdID0gZmFsc2U7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9CiAgICBib29sIGEgPSB0cnVlOwogICAgZm9yIChpbnQgaSA9IG47IGkgPD0gbTsgaSsrKSB7CiAgICAgICAgaWYgKGJbaV0pIHsKICAgICAgICAgICAgYSA9IGZhbHNlOwogICAgICAgICAgICBwcmludGYoIiVkXG4iLCBpKTsKICAgICAgICB9CiAgICB9CiAgICBpZiAoYSkgCiAgICAgICAgcHJpbnRmKCJBYnNlbnQiKTsKICAgIHJldHVybiAwOwp9",
        "stdin": "NTAwMDAwIDUxMDAwMA==",
        "expected_output": "NTAwMDA5CjUwMDAyOQo1MDAwNDEKNTAwMDU3CjUwMDA2OQo1MDAwODMKNTAwMTA3CjUwMDExMQo1MDAxMTMKNTAwMTE5CjUwMDE1Mwo1MDAxNjcKNTAwMTczCjUwMDE3Nwo1MDAxNzkKNTAwMTk3CjUwMDIwOQo1MDAyMzEKNTAwMjMzCjUwMDIzNwo1MDAyMzkKNTAwMjQ5CjUwMDI1Nwo1MDAyODcKNTAwMjk5CjUwMDMxNwo1MDAzMjEKNTAwMzMzCjUwMDM0MQo1MDAzNjMKNTAwMzY5CjUwMDM4OQo1MDAzOTMKNTAwNDEzCjUwMDQxNwo1MDA0MzEKNTAwNDQzCjUwMDQ1OQo1MDA0NzEKNTAwNDczCjUwMDQ4Mwo1MDA1MDEKNTAwNTA5CjUwMDUxOQo1MDA1MjcKNTAwNTY3CjUwMDU3OQo1MDA1ODcKNTAwNjAzCjUwMDYyOQo1MDA2NzEKNTAwNjc3CjUwMDY5Mwo1MDA2OTkKNTAwNzEzCjUwMDcxOQo1MDA3MjMKNTAwNzI5CjUwMDc0MQo1MDA3NzcKNTAwNzkxCjUwMDgwNwo1MDA4MDkKNTAwODMxCjUwMDgzOQo1MDA4NjEKNTAwODczCjUwMDg4MQo1MDA4ODcKNTAwODkxCjUwMDkwOQo1MDA5MTEKNTAwOTIxCjUwMDkyMwo1MDA5MzMKNTAwOTQ3CjUwMDk1Mwo1MDA5NTcKNTAwOTc3CjUwMTAwMQo1MDEwMTMKNTAxMDE5CjUwMTAyOQo1MDEwMzEKNTAxMDM3CjUwMTA0Mwo1MDEwNzcKNTAxMDg5CjUwMTEwMwo1MDExMjEKNTAxMTMxCjUwMTEzMwo1MDExMzkKNTAxMTU3CjUwMTE3Mwo1MDExODcKNTAxMTkxCjUwMTE5Nwo1MDEyMDMKNTAxMjA5CjUwMTIxNwo1MDEyMjMKNTAxMjI5CjUwMTIzMwo1MDEyNTcKNTAxMjcxCjUwMTI4Nwo1MDEyOTkKNTAxMzE3CjUwMTM0MQo1MDEzNDMKNTAxMzY3CjUwMTM4Mwo1MDE0MDEKNTAxNDA5CjUwMTQxOQo1MDE0MjcKNTAxNDUxCjUwMTQ2Mwo1MDE0OTMKNTAxNTAzCjUwMTUxMQo1MDE1NjMKNTAxNTc3CjUwMTU5Mwo1MDE2MDEKNTAxNjE3CjUwMTYyMwo1MDE2MzcKNTAxNjU5CjUwMTY5MQo1MDE3MDEKNTAxNzAzCjUwMTcwNwo1MDE3MTkKNTAxNzMxCjUwMTc2OQo1MDE3NzkKNTAxODAzCjUwMTgxNwo1MDE4MjEKNTAxODI3CjUwMTgyOQo1MDE4NDEKNTAxODYzCjUwMTg4OQo1MDE5MTEKNTAxOTMxCjUwMTk0Nwo1MDE5NTMKNTAxOTY3CjUwMTk3MQo1MDE5OTcKNTAyMDAxCjUwMjAxMwo1MDIwMzkKNTAyMDQzCjUwMjA1Nwo1MDIwNjMKNTAyMDc5CjUwMjA4MQo1MDIwODcKNTAyMDkzCjUwMjEyMQo1MDIxMzMKNTAyMTQxCjUwMjE3MQo1MDIxODEKNTAyMjE3CjUwMjIzNwo1MDIyNDcKNTAyMjU5CjUwMjI2MQo1MDIyNzcKNTAyMzAxCjUwMjMyMQo1MDIzMzkKNTAyMzkzCjUwMjQwOQo1MDI0MjEKNTAyNDI5CjUwMjQ0MQo1MDI0NTEKNTAyNDg3CjUwMjQ5OQo1MDI1MDEKNTAyNTA3CjUwMjUxNwo1MDI1NDMKNTAyNTQ5CjUwMjU1Mwo1MDI1OTEKNTAyNTk3CjUwMjYxMwo1MDI2MzEKNTAyNjMzCjUwMjY0Mwo1MDI2NTEKNTAyNjY5CjUwMjY4Nwo1MDI2OTkKNTAyNzAzCjUwMjcxNwo1MDI3MjkKNTAyNzY5CjUwMjc3MQo1MDI3ODEKNTAyNzg3CjUwMjgwNwo1MDI4MTkKNTAyODI5CjUwMjg0MQo1MDI4NDcKNTAyODYxCjUwMjg4Mwo1MDI5MTkKNTAyOTIxCjUwMjkzNwo1MDI5NjEKNTAyOTczCjUwMzAwMwo1MDMwMTcKNTAzMDM5CjUwMzA1Mwo1MDMwNzcKNTAzMTIzCjUwMzEzMQo1MDMxMzcKNTAzMTQ3CjUwMzE1OQo1MDMxOTcKNTAzMjA3CjUwMzIxMwo1MDMyMjcKNTAzMjMxCjUwMzIzMwo1MDMyNDkKNTAzMjY3CjUwMzI4Nwo1MDMyOTcKNTAzMzAzCjUwMzMxNwo1MDMzMzkKNTAzMzUxCjUwMzM1OQo1MDMzNjkKNTAzMzgxCjUwMzM4Mwo1MDMzODkKNTAzNDA3CjUwMzQxMwo1MDM0MjMKNTAzNDMxCjUwMzQ0MQo1MDM0NTMKNTAzNDgzCjUwMzUwMQo1MDM1NDMKNTAzNTQ5CjUwMzU1MQo1MDM1NjMKNTAzNTkzCjUwMzU5OQo1MDM2MDkKNTAzNjExCjUwMzYyMQo1MDM2MjMKNTAzNjQ3CjUwMzY1Mwo1MDM2NjMKNTAzNzA3CjUwMzcxNwo1MDM3NDMKNTAzNzUzCjUwMzc3MQo1MDM3NzcKNTAzNzc5CjUwMzc5MQo1MDM4MDMKNTAzODE5CjUwMzgyMQo1MDM4MjcKNTAzODUxCjUwMzg1Nwo1MDM4NjkKNTAzODc5CjUwMzkxMQo1MDM5MjcKNTAzOTI5CjUwMzkzOQo1MDM5NDcKNTAzOTU5CjUwMzk2Mwo1MDM5NjkKNTAzOTgzCjUwMzk4OQo1MDQwMDEKNTA0MDExCjUwNDAxNwo1MDQwNDcKNTA0MDYxCjUwNDA3Mwo1MDQxMDMKNTA0MTIxCjUwNDEzOQo1MDQxNDMKNTA0MTQ5CjUwNDE1MQo1MDQxNTcKNTA0MTgxCjUwNDE4Nwo1MDQxOTcKNTA0MjA5CjUwNDIyMQo1MDQyNDcKNTA0MjY5CjUwNDI4OQo1MDQyOTkKNTA0MzA3CjUwNDMxMQo1MDQzMjMKNTA0MzM3CjUwNDM0OQo1MDQzNTMKNTA0MzU5CjUwNDM3Nwo1MDQzNzkKNTA0Mzg5CjUwNDQwMwo1MDQ0NTcKNTA0NDYxCjUwNDQ3Mwo1MDQ0NzkKNTA0NTIxCjUwNDUyMwo1MDQ1MjcKNTA0NTQ3CjUwNDU2Mwo1MDQ1OTMKNTA0NTk5CjUwNDYwNwo1MDQ2MTcKNTA0NjE5CjUwNDYzMQo1MDQ2NjEKNTA0NjY3CjUwNDY3MQo1MDQ2NzcKNTA0NjgzCjUwNDcyNwo1MDQ3NjcKNTA0Nzg3CjUwNDc5Nwo1MDQ3OTkKNTA0ODE3CjUwNDgyMQo1MDQ4NTEKNTA0ODUzCjUwNDg1Nwo1MDQ4NzEKNTA0ODc3CjUwNDg5Mwo1MDQ5MDEKNTA0OTI5CjUwNDkzNwo1MDQ5NDMKNTA0OTQ3CjUwNDk1Mwo1MDQ5NjcKNTA0OTgzCjUwNDk4OQo1MDQ5OTEKNTA1MDI3CjUwNTAzMQo1MDUwMzMKNTA1MDQ5CjUwNTA1MQo1MDUwNjEKNTA1MDY3CjUwNTA3Mwo1MDUwOTEKNTA1MDk3CjUwNTExMQo1MDUxMTcKNTA1MTIzCjUwNTEyOQo1MDUxMzkKNTA1MTU3CjUwNTE1OQo1MDUxODEKNTA1MTg3CjUwNTIwMQo1MDUyMTMKNTA1MjMxCjUwNTIzNwo1MDUyNzcKNTA1Mjc5CjUwNTI4Mwo1MDUzMDEKNTA1MzEzCjUwNTMxOQo1MDUzMjEKNTA1MzI3CjUwNTMzOQo1MDUzNTcKNTA1MzY3CjUwNTM2OQo1MDUzOTkKNTA1NDA5CjUwNTQxMQo1MDU0MjkKNTA1NDQ3CjUwNTQ1OQo1MDU0NjkKNTA1NDgxCjUwNTQ5Mwo1MDU1MDEKNTA1NTExCjUwNTUxMwo1MDU1MjMKNTA1NTM3CjUwNTU1OQo1MDU1NzMKNTA1NjAxCjUwNTYwNwo1MDU2MTMKNTA1NjE5CjUwNTYzMwo1MDU2MzkKNTA1NjQzCjUwNTY1Nwo1MDU2NjMKNTA1NjY5CjUwNTY5MQo1MDU2OTMKNTA1NzA5CjUwNTcxMQo1MDU3MjcKNTA1NzU5CjUwNTc2Mwo1MDU3NzcKNTA1NzgxCjUwNTgxMQo1MDU4MTkKNTA1ODIzCjUwNTg2Nwo1MDU4NzEKNTA1ODc3CjUwNTkwNwo1MDU5MTkKNTA1OTI3CjUwNTk0OQo1MDU5NjEKNTA1OTY5CjUwNTk3OQo1MDYwNDcKNTA2MDcxCjUwNjA4Mwo1MDYxMDEKNTA2MTEzCjUwNjExOQo1MDYxMzEKNTA2MTQ3CjUwNjE3MQo1MDYxNzMKNTA2MTgzCjUwNjIwMQo1MDYyMTMKNTA2MjUxCjUwNjI2Mwo1MDYyNjkKNTA2MjgxCjUwNjI5MQo1MDYzMjcKNTA2MzI5CjUwNjMzMwo1MDYzMzkKNTA2MzQ3CjUwNjM1MQo1MDYzNTcKNTA2MzgxCjUwNjM5Mwo1MDY0MTcKNTA2NDIzCjUwNjQ0OQo1MDY0NTkKNTA2NDYxCjUwNjQ3OQo1MDY0OTEKNTA2NTAxCjUwNjUwNwo1MDY1MzEKNTA2NTMzCjUwNjUzNwo1MDY1NTEKNTA2NTYzCjUwNjU3Mwo1MDY1OTEKNTA2NTkzCjUwNjU5OQo1MDY2MDkKNTA2NjI5CjUwNjY0Nwo1MDY2NjMKNTA2NjgzCjUwNjY4Nwo1MDY2ODkKNTA2Njk5CjUwNjcyOQo1MDY3MzEKNTA2NzQzCjUwNjc3Mwo1MDY3ODMKNTA2NzkxCjUwNjc5Nwo1MDY4MDkKNTA2ODM3CjUwNjg0Mwo1MDY4NjEKNTA2ODczCjUwNjg4Nwo1MDY4OTMKNTA2ODk5CjUwNjkwMwo1MDY5MTEKNTA2OTI5CjUwNjk0MQo1MDY5NjMKNTA2OTgzCjUwNjk5Mwo1MDY5OTkKNTA3MDI5CjUwNzA0OQo1MDcwNzEKNTA3MDc3CjUwNzA3OQo1MDcxMDMKNTA3MTA5CjUwNzExMwo1MDcxMTkKNTA3MTM3CjUwNzEzOQo1MDcxNDkKNTA3MTUxCjUwNzE2Mwo1MDcxOTMKNTA3MTk3CjUwNzIxNwo1MDcyODkKNTA3MzAxCjUwNzMxMwo1MDczMTcKNTA3MzI5CjUwNzM0Nwo1MDczNDkKNTA3MzU5CjUwNzM2MQo1MDczNzEKNTA3MzgzCjUwNzQwMQo1MDc0MjEKNTA3NDMxCjUwNzQ2MQo1MDc0OTEKNTA3NDk3CjUwNzQ5OQo1MDc1MDMKNTA3NTIzCjUwNzU1Nwo1MDc1NzEKNTA3NTg5CjUwNzU5Mwo1MDc1OTkKNTA3NjA3CjUwNzYzMQo1MDc2NDEKNTA3NjY3CjUwNzY3Mwo1MDc2OTEKNTA3Njk3CjUwNzcxMwo1MDc3MTkKNTA3NzQzCjUwNzc1Nwo1MDc3NzkKNTA3NzgxCjUwNzc5Nwo1MDc4MDMKNTA3ODA5CjUwNzgyMQo1MDc4MjcKNTA3ODM5CjUwNzg4Mwo1MDc5MDEKNTA3OTA3CjUwNzkxNwo1MDc5MTkKNTA3OTM3CjUwNzk1Mwo1MDc5NjEKNTA3OTcxCjUwNzk3OQo1MDgwMDkKNTA4MDE5CjUwODAyMQo1MDgwMzMKNTA4MDM3CjUwODA3Mwo1MDgwODcKNTA4MDkxCjUwODA5Nwo1MDgxMDMKNTA4MTI5CjUwODE1OQo1MDgxNzEKNTA4MTg3CjUwODIxMwo1MDgyMjMKNTA4MjI5CjUwODIzNwo1MDgyNDMKNTA4MjU5CjUwODI3MQo1MDgyNzMKNTA4Mjk3CjUwODMwMQo1MDgzMjcKNTA4MzMxCjUwODM0OQo1MDgzNjMKNTA4MzY3CjUwODM3Mwo1MDgzOTMKNTA4NDMzCjUwODQzOQo1MDg0NTEKNTA4NDcxCjUwODQ3Nwo1MDg0ODkKNTA4NDk5CjUwODUxMwo1MDg1MTcKNTA4NTMxCjUwODU0OQo1MDg1NTkKNTA4NTY3CjUwODU3Nwo1MDg1NzkKNTA4NTgzCjUwODYxOQo1MDg2MjEKNTA4NjM3CjUwODY0Mwo1MDg2NjEKNTA4NjkzCjUwODcwOQo1MDg3MjcKNTA4NzcxCjUwODc4OQo1MDg3OTkKNTA4ODExCjUwODgxNwo1MDg4NDEKNTA4ODQ3CjUwODg2Nwo1MDg5MDEKNTA4OTAzCjUwODkwOQo1MDg5MTMKNTA4OTE5CjUwODkzMQo1MDg5NDMKNTA4OTUxCjUwODk1Nwo1MDg5NjEKNTA4OTY5CjUwODk3Mwo1MDg5ODcKNTA5MDIzCjUwOTAyNwo1MDkwNTMKNTA5MDYzCjUwOTA3MQo1MDkwODcKNTA5MTAxCjUwOTEyMwo1MDkxMzcKNTA5MTQ3CjUwOTE0OQo1MDkyMDMKNTA5MjIxCjUwOTIyNwo1MDkyMzkKNTA5MjYzCjUwOTI4MQo1MDkyODcKNTA5MjkzCjUwOTI5Nwo1MDkzMTcKNTA5MzI5CjUwOTM1OQo1MDkzNjMKNTA5Mzg5CjUwOTM5Mwo1MDk0MTMKNTA5NDE3CjUwOTQyOQo1MDk0NDEKNTA5NDQ5CjUwOTQ3Nwo1MDk1MTMKNTA5NTIxCjUwOTU0Mwo1MDk1NDkKNTA5NTU3CjUwOTU2Mwo1MDk1NjkKNTA5NTczCjUwOTU4MQo1MDk1OTEKNTA5NjAzCjUwOTYyMwo1MDk2MzMKNTA5NjQ3CjUwOTY1Mwo1MDk2NTkKNTA5NjgxCjUwOTY4Nwo1MDk2ODkKNTA5NjkzCjUwOTY5OQo1MDk3MjMKNTA5NzMxCjUwOTczNwo1MDk3NDEKNTA5NzY3CjUwOTc4Mwo1MDk3OTcKNTA5ODAxCjUwOTgzMwo1MDk4MzcKNTA5ODQzCjUwOTg2Mwo1MDk4NjcKNTA5ODc5CjUwOTkwOQo1MDk5MTEKNTA5OTIxCjUwOTkzOQo1MDk5NDcKNTA5OTU5CjUwOTk2Mwo1MDk5ODkK",
        "compiler_options": None,
        "command_line_args": None,
        "time_limit": 5,
        "extra_time": 0.5,
        "wall_time_limit": 3,
        "memory_limit": 128000,
        "redirect_stderr_to_stdout": True,
        "enable_network": False,
        "max_file_size": 1024
    }
    for i in range(20):
        batch_data["submissions"].append(submission_data)
    async with httpx.AsyncClient() as client:
        print("Тест 2: Создание пакетной отправки")
        resp = await client.post(f"{API_URL}/auth/login/", json=user_data)
        assert resp.status_code == 200, f"Auth error: {resp.text}"
        tokens = resp.json()
        access_token = tokens["access_token"]
        
        headers = {"Authorization": f"Bearer {access_token}"}
        resp = await client.post(f"{API_URL}/submissions/batch/", json=batch_data, headers=headers)
        assert resp.status_code == 201, resp.text
        print(f"Результаты теста: HTTP {resp.status_code} => {resp.json()['batch_token']}")
